using System.Text.Json.Nodes;
using AutoNate.Web.Services.Workflow;
using AutoNate.Web.Tests.Infrastructure;
using Xunit;

namespace AutoNate.Web.Tests.Workflow;

/// <summary>
/// Auton8's placement validation, checked against what the engine actually does (#324).
/// </summary>
/// <remarks>
/// <para>
/// Four hand-written placement rules preceded this, each complete with respect to
/// the defect already known and blind to the next: #158 → #289 → #309 → #321.
/// The pattern was the finding, not the individual rules.
/// </para>
/// <para>
/// So the cells are <b>derived</b>, from <c>src/shared/bpmn-placement.json</c>,
/// which <c>tools/bpmn-placement-probe/probe.py</c> generated by deploying 225
/// minimal documents to a live Flowable 8.0.0 and recording the verdict per cell.
/// Nothing here is reasoned; a cell that disagrees with the engine fails.
/// </para>
/// <para>
/// <b>This runs in CI, and that is the point.</b> Its sibling
/// <c>StartEventPlacementDifferentialTests</c> asks the same question of a live
/// engine and is <c>RequiresService=Flowable</c>, so it is outside the gate —
/// which is how #333's broken cardinality survived four rounds. This half needs
/// no engine: it compares Auton8's validation against the <em>recorded</em>
/// matrix, so Auton8 drifting from the engine fails the merge. The engine
/// changing under the recording is the other half's job.
/// </para>
/// </remarks>
public sealed class PlacementDifferentialTests
{
    private static string PlacementPath =>
        Path.Combine(RepoRoot.Path, "src", "shared", "bpmn-placement.json");

    private sealed record Cell(string Position, string Definition, string Container, bool EngineAccepts);

    private static IReadOnlyList<Cell> Cells()
    {
        var document = JsonNode.Parse(File.ReadAllText(PlacementPath))!;
        var containers = document["containers"]!.AsArray()
            .Select(c => c!.GetValue<string>()).ToList();

        var cells = new List<Cell>();
        foreach (var rule in document["rules"]!.AsArray())
        {
            var position = rule!["position"]!.GetValue<string>();
            var definition = rule["eventDefinition"]!.GetValue<string>();
            var allowed = (rule["allowedContainers"]?.AsArray() ?? [])
                .Select(c => c!.GetValue<string>())
                .ToHashSet(StringComparer.Ordinal);

            foreach (var container in containers)
            {
                // A rule lists a container in exactly one of the two arrays, or in
                // neither when the cell was not constructible (a timer end event
                // has no form in the schema). Skip what was never measured rather
                // than inventing a verdict for it.
                var refused = (rule["refusedContainers"]?.AsArray() ?? [])
                    .Select(c => c!.GetValue<string>())
                    .ToHashSet(StringComparer.Ordinal);
                if (!allowed.Contains(container) && !refused.Contains(container)) continue;

                cells.Add(new Cell(position, definition, container, allowed.Contains(container)));
            }
        }

        return cells;
    }

    [Fact]
    public void The_recorded_matrix_is_substantial_and_measured()
    {
        var document = JsonNode.Parse(File.ReadAllText(PlacementPath))!;

        Assert.Equal("8.0.0", document["flowableVersion"]?.GetValue<string>());
        Assert.Contains(
            "deployed",
            document["generatedFrom"]?.GetValue<string>() ?? "",
            StringComparison.OrdinalIgnoreCase);

        var cells = Cells();

        // A floor. A file that lost its rules, or a reader that stopped finding
        // them, would otherwise report a clean tree forever -- the failure this
        // milestone has found more than any other.
        Assert.True(
            cells.Count > 150,
            $"The placement matrix yielded {cells.Count} cells. It was measured with 225; "
            + "something is not being read (#324).");

        Assert.Contains(cells, c => !c.EngineAccepts);
        Assert.Contains(cells, c => c.EngineAccepts);
    }

    /// <summary>
    /// The container axis exists because six cells need it (#324, #289, #309).
    /// </summary>
    /// <remarks>
    /// Measured: 6 of the 45 (position, definition) pairs change verdict with the
    /// container, and <b>all six are start events</b>. That measurement is what
    /// decided placement lives in its own file rather than as a column on
    /// <c>bpmn-support.json</c>'s 69 rows, so it is pinned: if it ever stops being
    /// true, the reason for the file's shape has changed and someone should know.
    /// </remarks>
    [Fact]
    public void Container_dependence_is_confined_to_start_events()
    {
        var dependent = JsonNode.Parse(File.ReadAllText(PlacementPath))!["rules"]!.AsArray()
            .Where(r => r!["containerDependent"]!.GetValue<bool>())
            .Select(r => $"{r!["position"]!.GetValue<string>()}/{r["eventDefinition"]!.GetValue<string>()}")
            .Order(StringComparer.Ordinal)
            .ToList();

        Assert.Equal(
            "start/conditional, start/error, start/escalation, start/message, start/signal, start/timer",
            string.Join(", ", dependent));
    }

    /// <summary>
    /// Compensation cannot start an event subprocess, and now there is a cell (#324, #321).
    /// </summary>
    /// <remarks>
    /// The allow-list carried <c>compensateEventDefinition</c> for the event
    /// subprocess and the engine refuses it — measured,
    /// <c>flowable-event-subprocess-invalid-start-event-definition</c>. #321
    /// removed the row; what it could not add was a cell that would have caught
    /// it, because the differential test had no compensate column. This is that
    /// cell.
    /// </remarks>
    [Fact]
    public void Compensation_cannot_start_an_event_subprocess()
    {
        var cell = Cells().Single(c =>
            c.Position == "start" && c.Definition == "compensate" && c.Container == "eventSubProcess");

        Assert.False(
            cell.EngineAccepts,
            "The recorded matrix says Flowable accepts a compensation start event in an "
            + "event subprocess. It does not -- measured, it answers "
            + "flowable-event-subprocess-invalid-start-event-definition. If this changed, "
            + "re-run tools/bpmn-placement-probe/probe.py rather than editing the file (#324).");

        var engineCodes = JsonNode.Parse(File.ReadAllText(PlacementPath))!["rules"]!.AsArray()
            .Single(r => r!["position"]!.GetValue<string>() == "start"
                         && r["eventDefinition"]!.GetValue<string>() == "compensate")
            ["engineCodes"]!.AsArray().Select(c => c!.GetValue<string>()).ToList();

        Assert.Contains("flowable-event-subprocess-invalid-start-event-definition", engineCodes);

        // ...AND the allow-list itself, which is what would actually have caught it.
        //
        // Asserting only that publish refuses the diagram is the loose oracle #321
        // found: Compensation Start Event is ALSO withdrawn by the manifest (#107),
        // so an unrelated refusal satisfies a `Count > 0` check and the allow-list
        // row can be restored with the suite green. Proven -- re-adding
        // `compensateEventDefinition` here left 43/43 passing until this assertion
        // existed.
        var allowed = AllowedDefinitionsFor("EventSubProcess");

        Assert.DoesNotContain("compensateEventDefinition", allowed);
    }

    /// <summary>The start-event allow-list for one container, read from the product.</summary>
    /// <remarks>
    /// Reflection because the table is private and should stay private: the point
    /// is to assert what the product actually carries, not to widen its surface
    /// so a test can see it.
    /// </remarks>
    private static IReadOnlyCollection<string> AllowedDefinitionsFor(string container)
    {
        var type = typeof(WorkflowBpmnXml);
        var table = type
            .GetField("StartEventDefinitionsAllowed",
                System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static)
            ?.GetValue(null);

        Assert.True(
            table is not null,
            "WorkflowBpmnXml.StartEventDefinitionsAllowed is gone or renamed. If the allow-list "
            + "moved, point this guard at its new home -- a reflection lookup that silently finds "
            + "nothing asserts nothing (#324).");

        var containerType = type.GetNestedType("StartEventContainer",
            System.Reflection.BindingFlags.NonPublic)!;
        var key = Enum.Parse(containerType, container);

        var indexer = table!.GetType().GetProperty("Item")!;
        var set = (System.Collections.IEnumerable)indexer.GetValue(table, [key])!;

        return set.Cast<string>().ToList();
    }

    /// <summary>
    /// Auton8 refuses every start placement the engine refuses (#324).
    /// </summary>
    /// <remarks>
    /// Only start events, because only start events are container-dependent —
    /// asserting the other four positions here would be asserting that Auton8
    /// agrees with a constant, which is true of any implementation.
    /// </remarks>
    [Theory]
    [MemberData(nameof(StartCells))]
    public void Auton8_refuses_what_the_engine_refuses(string definition, string container, bool engineAccepts)
    {
        var xml = Diagram(definition, container);
        var errors = WorkflowBpmnXml.ValidateProcess(xml).Errors;

        if (StricterThanTheEngine.TryGetValue((definition, container), out var departure))
        {
            // AC6: BOTH sides, so a row cannot silently switch a cell off. The
            // engine half comes from the recorded matrix rather than from this
            // table, so a departure that stops being a departure fails here
            // instead of quietly becoming an ordinary agreement.
            Assert.True(
                engineAccepts,
                $"({definition}, {container}) is declared a deliberate departure -- Auton8 "
                + "stricter than the engine -- but the measured matrix says the engine "
                + "refuses it too. Then it is not a departure, and this row is claiming a "
                + "decision where there is none. Remove it (#324).");

            Assert.True(
                errors.Any(e => e.Contains(departure.RefusalPhrase, StringComparison.Ordinal)),
                $"({definition}, {container}) is declared a departure for this reason:\n  "
                + $"{departure.Reason}\n\nbut nothing Auton8 said contains "
                + $"\"{departure.RefusalPhrase}\". Errors were:\n  "
                + string.Join("\n  ", errors)
                + "\n\nEach departure names the phrase that proves ITS OWN refusal, because a "
                + "departure is refused by a different rule than placement. Matching anything "
                + "at all would assert nothing (#321).");
            return;
        }

        if (engineAccepts)
        {
            // A FALSE REFUSAL is the expensive direction: the author is told no
            // about a diagram that would have run.
            Assert.True(
                errors.Count == 0,
                $"Auton8 refuses a {definition} start event in a {container}, which Flowable "
                + $"ACCEPTS (measured):\n  {string.Join("\n  ", errors)}");
            return;
        }

        Assert.True(
            errors.Count > 0,
            $"Flowable refuses a {definition} start event in a {container} (measured) and "
            + "Auton8 publishes it, so the author finds out from the engine instead of "
            + "from the studio (#289, #309, #324).");
    }

    public static TheoryData<string, string, bool> StartCells()
    {
        var data = new TheoryData<string, string, bool>();
        foreach (var cell in Cells().Where(c => c.Position == "start"))
        {
            data.Add(cell.Definition, cell.Container, cell.EngineAccepts);
        }

        return data;
    }


    private readonly record struct Departure(string Reason, string RefusalPhrase);

    /// <summary>
    /// Cells where Auton8 deliberately refuses something the engine accepts (#324).
    /// </summary>
    /// <remarks>
    /// The honest way to be stricter than the engine is to say so in one place,
    /// not to weaken the test that would otherwise catch it. Each entry names the
    /// phrase that proves <b>its own</b> refusal: a departure is refused by a
    /// different rule than placement, so matching the placement rule's phrase
    /// would assert the wrong thing and matching anything at all would assert
    /// nothing (#321).
    /// </remarks>
    private static readonly Dictionary<(string Definition, string Container), Departure> StricterThanTheEngine =
        new()
        {
            [("none", "eventSubProcess")] = new(
                Reason:
                    "an event subprocess is triggered BY its start event, so a bare one can never "
                    + "trigger at all -- Flowable deploys it and it silently never runs, which looks "
                    + "exactly like its event never happening",
                RefusalPhrase: "starts with a plain start event"),

            [("none", "adHocSubProcess")] = new(
                Reason:
                    "#163: an ad-hoc subprocess with no completion condition can never finish, so "
                    + "the process stops inside it. The engine deploys it happily and the instance "
                    + "parks forever, which is the failure mode hardest to diagnose from outside",
                RefusalPhrase: "has no completion condition"),

            [("none", "transaction")] = new(
                Reason:
                    "#220/#228: the container deploys and runs, but its distinguishing behaviour -- "
                    + "rollback via cancel events -- does not. Offering it would be offering a "
                    + "subprocess under a name that promises rollback it cannot do",
                RefusalPhrase: "cannot be deployed"),
        };


    /// <summary>
    /// The other four positions agree with the engine too (#324 AC5).
    /// </summary>
    /// <remarks>
    /// <para>
    /// Catch, throw, boundary and end are container-INDEPENDENT in every measured
    /// cell, so these are asserted once per (position, definition) against the
    /// process container rather than five times against a constant.
    /// </para>
    /// <para>
    /// Auton8 is allowed to be quieter here than at publish: this asks only that
    /// it does not ACCEPT what the engine refuses. A false refusal on these
    /// positions would be caught by the manifest's own guards, which iterate rows
    /// this file deliberately does not duplicate.
    /// </para>
    /// </remarks>
    [Theory]
    [MemberData(nameof(NonStartCells))]
    public void Auton8_does_not_accept_what_the_engine_refuses_elsewhere(
        string position, string definition, bool engineAccepts)
    {
        if (engineAccepts) return;   // the permissive direction is the manifest's job

        var errors = WorkflowBpmnXml.ValidateProcess(Diagram(definition, "process", position)).Errors;

        if (OpenGaps.Contains((position, definition)))
        {
            // BOTH sides, exactly as a declared departure asserts both (#324 AC6).
            // The engine half is already true by the branch above. This half says
            // Auton8 still accepts it -- so the day someone closes the gap, this
            // goes red and asks for the row to be deleted. A table of known gaps
            // that did not fail on being fixed would be a list nobody prunes.
            Assert.True(
                errors.Count == 0,
                $"({position}, {definition}) is listed as an open gap -- #402 -- but Auton8 now "
                + "refuses it. Good: delete the row from OpenGaps, and this cell becomes an "
                + "ordinary agreement.");
            return;
        }

        Assert.True(
            errors.Count > 0,
            $"Flowable refuses a {definition} {position} event (measured) and Auton8 publishes "
            + "it, so the author finds out from the engine instead of from the studio (#324).");
    }

    /// <summary>
    /// Cells where the engine refuses and Auton8 does not, yet (#324, #402).
    /// </summary>
    /// <remarks>
    /// <para>
    /// Found by this test on its first run over the non-start positions. Every one
    /// of these is <b>unreachable from the studio</b>: ten have no
    /// <c>bpmn-palette.json</c> row at all and the eleventh is
    /// <c>studio: withdrawn</c>, so no author can draw one. They are reachable by
    /// IMPORTING a diagram, which is a real path, and that is #402.
    /// </para>
    /// <para>
    /// Listed rather than fixed here because closing them is eleven new product
    /// refusals and a decision about how strict publish should be about diagrams
    /// it did not author — a decision, not a defect, and outside what this story
    /// asked for. Listed rather than ignored because a gap nobody wrote down is
    /// how the last four placement rules each came to be blind to the next one.
    /// </para>
    /// </remarks>
    private static readonly HashSet<(string Position, string Definition)> OpenGaps =
    [
        ("boundary", "link"),
        ("boundary", "terminate"),
        ("intermediateCatch", "compensate"),
        ("intermediateCatch", "error"),
        ("intermediateCatch", "escalation"),
        ("intermediateCatch", "none"),
        ("intermediateCatch", "terminate"),
        ("intermediateThrow", "conditional"),
        ("intermediateThrow", "error"),
        ("intermediateThrow", "message"),
        ("intermediateThrow", "timer"),
    ];

    /// <summary>The gap list cannot grow quietly (#324).</summary>
    [Fact]
    public void The_open_placement_gaps_are_these_eleven()
    {
        // A literal, deliberately. Every other expectation in this file derives
        // from the measured matrix; this one is a record of a decision, and a
        // twelfth gap should be an edit a reviewer sees rather than a number that
        // moved.
        Assert.Equal(11, OpenGaps.Count);
    }

    public static TheoryData<string, string, bool> NonStartCells()
    {
        var data = new TheoryData<string, string, bool>();
        foreach (var cell in Cells().Where(c => c.Position != "start" && c.Container == "process"))
        {
            data.Add(cell.Position, cell.Definition, cell.EngineAccepts);
        }

        return data;
    }

    /// <summary>The same minimal document the probe deployed, rebuilt here.</summary>
    private static string Diagram(string definition, string container, string position = "start")
    {
        var (root, child) = definition switch
        {
            "none" => ("", ""),
            "message" => ("""<message id="Msg_1" name="m"/>""", """<messageEventDefinition messageRef="Msg_1"/>"""),
            "timer" => ("", """<timerEventDefinition><timeDuration>PT5M</timeDuration></timerEventDefinition>"""),
            "signal" => ("""<signal id="Sig_1" name="s"/>""", """<signalEventDefinition signalRef="Sig_1"/>"""),
            "conditional" => ("", """<conditionalEventDefinition><condition>${ok}</condition></conditionalEventDefinition>"""),
            "error" => ("""<error id="Err_1" name="e" errorCode="E"/>""", """<errorEventDefinition errorRef="Err_1"/>"""),
            "escalation" => ("""<escalation id="Esc_1" name="x" escalationCode="X"/>""", """<escalationEventDefinition escalationRef="Esc_1"/>"""),
            "compensate" => ("", """<compensateEventDefinition/>"""),
            "terminate" => ("", """<terminateEventDefinition/>"""),
            "link" => ("", """<linkEventDefinition name="L"/>"""),
            _ => throw new ArgumentOutOfRangeException(nameof(definition), definition, "unmeasured definition"),
        };

        const string Host = """<userTask id="Host_1" name="host"/>""";

        var element = position switch
        {
            "start" => $"""<startEvent id="Ev_1">{child}</startEvent>""",
            "intermediateCatch" => $"""<intermediateCatchEvent id="Ev_1">{child}</intermediateCatchEvent>""",
            "intermediateThrow" => $"""<intermediateThrowEvent id="Ev_1">{child}</intermediateThrowEvent>""",
            // A boundary event attaches to an activity, never to a container --
            // which is why it cannot be container-dependent and the measurement
            // says it is not.
            "boundary" => $"""<boundaryEvent id="Ev_1" attachedToRef="Host_1">{child}</boundaryEvent>""",
            "end" => $"""<endEvent id="Ev_1">{child}</endEvent>""",
            _ => throw new ArgumentOutOfRangeException(nameof(position), position, "unmeasured position"),
        };

        // Anything that is not itself a start event needs one beside it, so a
        // "no start event" refusal cannot be mistaken for this cell's verdict.
        var opener = position == "start" ? "" : """<startEvent id="Start_1"/>""";

        var body = container switch
        {
            "process" => $"{opener}{element}{Host}",
            "eventSubProcess" => $"""<startEvent id="Start_0"/><subProcess id="Sub_1" triggeredByEvent="true">{opener}{element}{Host}</subProcess>""",
            "embeddedSubProcess" => $"""<startEvent id="Start_0"/><subProcess id="Sub_1">{opener}{element}{Host}</subProcess>""",
            "adHocSubProcess" => $"""<startEvent id="Start_0"/><adHocSubProcess id="Sub_1">{opener}{element}{Host}</adHocSubProcess>""",
            "transaction" => $"""<startEvent id="Start_0"/><transaction id="Sub_1">{opener}{element}{Host}</transaction>""",
            _ => throw new ArgumentOutOfRangeException(nameof(container), container, "unmeasured container"),
        };

        return $"""
            <?xml version="1.0" encoding="UTF-8"?>
            <definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
                         xmlns:flowable="http://flowable.org/bpmn"
                         targetNamespace="http://autonate.dev/workflows">
              {root}
              <process id="Probe_1" name="probe" isExecutable="true">
                {body}
              </process>
            </definitions>
            """;
    }
}
