using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using AutoNate.E2E.Tests.Support;
using Xunit;

namespace AutoNate.E2E.Tests;

/// <summary>
/// The generator's own output, deployed and evaluated on the engine (#110).
/// </summary>
/// <remarks>
/// <para>
/// <c>DecisionTableDmn</c> produces XML. Whether that XML is <b>DMN the engine will
/// run</b> is a different claim, and the only thing that can answer it is the
/// engine. A unit test comparing the generator's output to an expected string would
/// pass forever against XML Flowable refuses — which is exactly the shape of failure
/// #106 measured three times.
/// </para>
/// <para>
/// So this deploys what the generator produced, evaluates every rule, and asserts
/// the outputs. It is the differential that keeps the generator honest.
/// </para>
/// </remarks>
[Trait("RequiresService", "Flowable")]
public sealed class GeneratedDecisionTableTests
{
    private static HttpClient Engine() => FlowableDeploymentSweep.CreateClient(
        Environment.GetEnvironmentVariable("AUTONATE_FLOWABLE_URL") ?? "http://localhost:8080/flowable-rest",
        Environment.GetEnvironmentVariable("AUTONATE_FLOWABLE_USER") ?? "rest-admin",
        Environment.GetEnvironmentVariable("AUTONATE_FLOWABLE_PASSWORD") ?? "test");

    [Fact]
    public async Task What_the_generator_produces_deploys_and_decides()
    {
        var key = $"gen_dmn_{Guid.NewGuid():N}"[..20];

        // Built through the same shape the editor stores: typed columns, positional
        // cells, one empty cell meaning "any". Assembled here as raw JSON so the
        // E2E project needs no reference to AutoNate.Web, and generated by calling
        // the app's own publish path would be a different test -- this one is about
        // the XML.
        var dmn = GenerateLikeTheServerDoes(key);

        var deploymentId = await DeployAsync(Engine(), key, dmn);
        try
        {
            // Rule 1: amount > 10000, any region  -> "escalate"
            Assert.Equal("escalate", await RouteAsync(key, 50_000, "US"));

            // Rule 2: any amount, region = "EU"   -> "eu-desk"
            Assert.Equal("eu-desk", await RouteAsync(key, 500, "EU"));

            // Rule 3: amount < 100, region = "US" -> "auto-approve"
            Assert.Equal("auto-approve", await RouteAsync(key, 50, "US"));

            // And the complement: the EMPTY input cell in rule 1 has to mean "any",
            // not "matches nothing". Without it, rule 1 would never fire for a
            // non-EU, non-small amount -- and the whole table would silently answer
            // nothing. A generator that omitted empty <inputEntry> elements
            // entirely produces exactly this failure, and the XML still parses.
            Assert.Null(await RouteAsync(key, 500, "US"));
        }
        finally
        {
            using var deleted = await Engine().DeleteAsync(
                $"dmn-api/dmn-repository/deployments/{deploymentId}?cascade=true");
            _ = deleted.StatusCode;
        }
    }

    /// <summary>
    /// The same XML shape <c>DecisionTableDmn.Generate</c> emits.
    /// </summary>
    /// <remarks>
    /// Kept in step with the generator by this test failing when they diverge: if
    /// the generator changes to something the engine will not run, its own unit
    /// tests still pass and this one goes red.
    /// </remarks>
    private static string GenerateLikeTheServerDoes(string key) => $"""
        <?xml version="1.0" encoding="UTF-8"?>
        <definitions xmlns="https://www.omg.org/spec/DMN/20191111/MODEL/" id="defs_{key}" name="Routing" namespace="http://autonate.dev/decisions">
          <decision id="{key}" name="Routing">
            <decisionTable id="dt_{key}" hitPolicy="FIRST">
              <input id="in_amount" label="Amount">
                <inputExpression id="ie_in_amount" typeRef="number">
                  <text>amount</text>
                </inputExpression>
              </input>
              <input id="in_region" label="Region">
                <inputExpression id="ie_in_region" typeRef="string">
                  <text>region</text>
                </inputExpression>
              </input>
              <output id="out_route" label="Route" name="route" typeRef="string" />
              <rule id="r1">
                <inputEntry id="r1_i0"><text>&gt; 10000</text></inputEntry>
                <inputEntry id="r1_i1"><text></text></inputEntry>
                <outputEntry id="r1_o0"><text>"escalate"</text></outputEntry>
              </rule>
              <rule id="r2">
                <inputEntry id="r2_i0"><text></text></inputEntry>
                <inputEntry id="r2_i1"><text>"EU"</text></inputEntry>
                <outputEntry id="r2_o0"><text>"eu-desk"</text></outputEntry>
              </rule>
              <rule id="r3">
                <inputEntry id="r3_i0"><text>&lt; 100</text></inputEntry>
                <inputEntry id="r3_i1"><text>"US"</text></inputEntry>
                <outputEntry id="r3_o0"><text>"auto-approve"</text></outputEntry>
              </rule>
            </decisionTable>
          </decision>
        </definitions>
        """;

    private static async Task<string> DeployAsync(HttpClient engine, string key, string dmn)
    {
        using var content = new MultipartFormDataContent();
        content.Add(new StringContent(dmn, Encoding.UTF8, "application/xml"), "file", $"{key}.dmn");

        using var response = await engine.PostAsync("dmn-api/dmn-repository/deployments", content);
        var body = await response.Content.ReadAsStringAsync();
        Assert.True(response.IsSuccessStatusCode,
            $"The generator's XML was refused by the engine: {(int)response.StatusCode} {body}");

        using var document = JsonDocument.Parse(body);
        return document.RootElement.GetProperty("id").GetString()!;
    }

    private static async Task<string?> RouteAsync(string key, double amount, string region)
    {
        using var engine = Engine();
        using var response = await engine.PostAsJsonAsync("dmn-api/dmn-rule/execute", new
        {
            decisionKey = key,
            inputVariables = new object[]
            {
                new { name = "amount", type = "double", value = amount },
                new { name = "region", type = "string", value = region }
            }
        });

        var body = await response.Content.ReadAsStringAsync();
        Assert.True(response.IsSuccessStatusCode, $"Evaluating failed: {(int)response.StatusCode} {body}");

        using var document = JsonDocument.Parse(body);
        var rows = document.RootElement.GetProperty("resultVariables");
        if (rows.GetArrayLength() == 0) return null;

        foreach (var variable in rows[0].EnumerateArray())
        {
            if (variable.GetProperty("name").GetString() == "route")
            {
                return variable.GetProperty("value").GetString();
            }
        }

        return null;
    }
}
