using AutoNate.E2E.Tests.Support;
using Microsoft.Playwright;
using Xunit;

namespace AutoNate.E2E.Tests;

/// <summary>
/// Phase 2 of the comprehensive E2E plan
/// (<c>docs/plans/2026-05-29-playwright-e2e-coverage.md</c>) — the
/// highest-value journey: a custom record type seeded via API, then full
/// list / create / edit / watch / comment / history / delete coverage driven
/// through the UI on top of it. Filters / Columns popovers are exercised
/// separately because they don't need a created record.
///
/// Each test mints its own record type + record so the suite stays order
/// independent against the shared ephemeral DB, and destructive flows (the
/// delete test) are safe now that the DB is isolated from the developer's
/// working <c>AutoNate</c>.
/// </summary>
public sealed class RecordsCrudTests : E2ETestBase
{
    public RecordsCrudTests(AutoNateE2EFixture fixture) : base(fixture) { }

    [Fact]
    public async Task RecordList_RendersHeadingAndNewButton()
    {
        await using var session = await NewSignedInAsAdminAsync();
        var page = session.Page;
        var seeder = new ApiSeeder(page.APIRequest);

        var typeName = TestNames.Prefixed("asset");
        var type = await seeder.CreateRecordTypeAsync(TestNames.ShortCode(), typeName);

        await page.GotoAsync($"/records/{type.ShortCode}");

        // The PageHeader title renders `<code>{code}</code>{name}` adjacent
        // with no whitespace, so the accessible name has no space between
        // them ("E71898e2e-asset-…"). Just assert the h1 mounted and let the
        // New-button check below — whose aria-label encodes the type name —
        // prove the right record type was loaded.
        await Assertions.Expect(page.Locator("h1").First)
            .ToBeVisibleAsync(new() { Timeout = 10_000 });

        await Assertions.Expect(
            page.GetByRole(AriaRole.Button, new() { Name = $"New {type.Name}" }))
            .ToBeVisibleAsync();
    }

    [Fact]
    public async Task CreateRecord_ViaUi_LandsOnDetailPageWithProvidedName()
    {
        await using var session = await NewSignedInAsAdminAsync();
        var page = session.Page;
        var seeder = new ApiSeeder(page.APIRequest);

        var typeName = TestNames.Prefixed("widget");
        var type = await seeder.CreateRecordTypeAsync(TestNames.ShortCode(), typeName);

        await page.GotoAsync($"/records/{type.ShortCode}");
        await page.GetByRole(AriaRole.Button, new() { Name = $"New {type.Name}" }).ClickAsync();

        // RecordCreate's PageHeader title: "New {name} {code}".
        await Assertions.Expect(
            page.GetByRole(AriaRole.Heading,
                new() { Name = $"New {type.Name} {type.ShortCode}" }))
            .ToBeVisibleAsync(new() { Timeout = 10_000 });

        var recordName = TestNames.Prefixed("rec");
        await page.GetByLabel("Name").FillAsync(recordName);
        await page.GetByRole(AriaRole.Button, new() { Name = "Create" }).ClickAsync();

        // Landed on /record/{key} (key is autogenerated, e.g. "E3F8C1-1").
        await page.WaitForURLAsync(new System.Text.RegularExpressions.Regex(@"/record/[A-Z0-9]+-\d+"),
            new() { Timeout = 10_000 });

        await Assertions.Expect(page.GetByText(recordName).First)
            .ToBeVisibleAsync(new() { Timeout = 5_000 });
    }

    [Fact]
    public async Task EditRecordName_PersistsAcrossReload()
    {
        await using var session = await NewSignedInAsAdminAsync();
        var page = session.Page;
        var seeder = new ApiSeeder(page.APIRequest);

        var type = await seeder.CreateRecordTypeAsync(TestNames.ShortCode(), TestNames.Prefixed("item"));
        var record = await seeder.CreateRecordAsync(type.Id, TestNames.Prefixed("rec"));

        await page.GotoAsync($"/record/{record.Key}");

        var updatedName = TestNames.Prefixed("renamed");
        var nameField = page.GetByLabel("Name");
        await nameField.WaitForAsync(new() { Timeout = 10_000 });
        await nameField.FillAsync(updatedName);
        await page.GetByRole(AriaRole.Button, new() { Name = "Save" }).ClickAsync();

        // RecordDetail flashes a Mantine Alert with role=alert and text "Saved." on
        // successful PATCH.
        await Assertions.Expect(page.GetByText("Saved."))
            .ToBeVisibleAsync(new() { Timeout = 10_000 });

        await page.ReloadAsync();
        await Assertions.Expect(page.GetByLabel("Name"))
            .ToHaveValueAsync(updatedName, new() { Timeout = 10_000 });
    }

    [Fact]
    public async Task WatchToggle_FlipsLabelOnClick()
    {
        await using var session = await NewSignedInAsAdminAsync();
        var page = session.Page;
        var seeder = new ApiSeeder(page.APIRequest);

        var type = await seeder.CreateRecordTypeAsync(TestNames.ShortCode(), TestNames.Prefixed("doc"));
        var record = await seeder.CreateRecordAsync(type.Id, TestNames.Prefixed("rec"));

        await page.GotoAsync($"/record/{record.Key}");

        // Fresh record → not watched yet → trigger reads "Watch".
        var watch = page.GetByRole(AriaRole.Button, new() { Name = "Watch" });
        await Assertions.Expect(watch).ToBeVisibleAsync(new() { Timeout = 10_000 });
        await watch.ClickAsync();

        // Hitting POST /api/records/{id}/watchers flips the local watch state
        // and re-renders the ActionIcon with aria-label="Unwatch".
        await Assertions.Expect(
            page.GetByRole(AriaRole.Button, new() { Name = "Unwatch" }))
            .ToBeVisibleAsync(new() { Timeout = 5_000 });
    }

    [Fact]
    public async Task PostComment_AppearsInTheCommentsPanel()
    {
        await using var session = await NewSignedInAsAdminAsync();
        var page = session.Page;
        var seeder = new ApiSeeder(page.APIRequest);

        var type = await seeder.CreateRecordTypeAsync(TestNames.ShortCode(), TestNames.Prefixed("note"));
        var record = await seeder.CreateRecordAsync(type.Id, TestNames.Prefixed("rec"));

        await page.GotoAsync($"/record/{record.Key}");

        // The comments panel sits beneath the tab strip on RecordDetail (not
        // a tab itself) — wait for the heading first so we know it mounted.
        await Assertions.Expect(
            page.GetByRole(AriaRole.Heading, new() { Name = "Comments" }))
            .ToBeVisibleAsync(new() { Timeout = 10_000 });

        var commentText = $"e2e-comment-{TestNames.ShortSlug()}";
        await page.GetByPlaceholder("Add a comment...").FillAsync(commentText);
        await page.GetByRole(AriaRole.Button, new() { Name = "Post comment" }).ClickAsync();

        await Assertions.Expect(page.GetByText(commentText))
            .ToBeVisibleAsync(new() { Timeout = 10_000 });
    }

    [Fact]
    public async Task HistoryTab_ShowsRecordCreationEntry()
    {
        await using var session = await NewSignedInAsAdminAsync();
        var page = session.Page;
        var seeder = new ApiSeeder(page.APIRequest);

        var type = await seeder.CreateRecordTypeAsync(TestNames.ShortCode(), TestNames.Prefixed("hist"));
        var record = await seeder.CreateRecordAsync(type.Id, TestNames.Prefixed("rec"));

        await page.GotoAsync($"/record/{record.Key}");

        await page.GetByRole(AriaRole.Tab, new() { Name = "History" }).ClickAsync();

        // The RecordHistoryPanel renders the create as a "Created" entry —
        // verify it appears so we know the history endpoint resolved (an
        // error here would render an Alert and no entries).
        await Assertions.Expect(page.GetByText("Created").First)
            .ToBeVisibleAsync(new() { Timeout = 10_000 });
    }

    [Fact]
    public async Task DeleteRecord_RemovesItFromTheList()
    {
        await using var session = await NewSignedInAsAdminAsync();
        var page = session.Page;
        var seeder = new ApiSeeder(page.APIRequest);

        var type = await seeder.CreateRecordTypeAsync(TestNames.ShortCode(), TestNames.Prefixed("del"));
        var record = await seeder.CreateRecordAsync(type.Id, TestNames.Prefixed("rec"));

        await page.GotoAsync($"/record/{record.Key}");

        await page.GetByRole(AriaRole.Button, new() { Name = "Delete" }).ClickAsync();

        // Confirm in the Mantine modal (title "Delete record"). The destructive
        // confirm button is the red "Delete" Button inside the dialog.
        var dialog = page.GetByRole(AriaRole.Dialog);
        await Assertions.Expect(dialog).ToBeVisibleAsync(new() { Timeout = 5_000 });
        await dialog.GetByRole(AriaRole.Button, new() { Name = "Delete" }).ClickAsync();

        // After confirm the SPA navigates back to /records/{code}.
        await page.WaitForURLAsync($"**/records/{type.ShortCode}",
            new() { Timeout = 10_000 });

        // And the deleted record's key shouldn't appear anywhere on the list.
        await Assertions.Expect(page.GetByText(record.Key)).Not.ToBeVisibleAsync();
    }

    [Fact]
    public async Task FiltersAndColumnsPopovers_OpenAndShowControls()
    {
        await using var session = await NewSignedInAsAdminAsync();
        var page = session.Page;
        var seeder = new ApiSeeder(page.APIRequest);

        var type = await seeder.CreateRecordTypeAsync(TestNames.ShortCode(), TestNames.Prefixed("filtcol"));
        await page.GotoAsync($"/records/{type.ShortCode}");

        // Wait for the search input to confirm the toolbar mounted before
        // poking the popover triggers.
        await Assertions.Expect(page.GetByPlaceholder("Search records…"))
            .ToBeVisibleAsync(new() { Timeout = 10_000 });

        await page.GetByRole(AriaRole.Button, new() { Name = "Columns" }).ClickAsync();
        // The Columns popover lists every column with a drag handle aria-label.
        await Assertions.Expect(page.GetByLabel("Drag to reorder").First)
            .ToBeVisibleAsync(new() { Timeout = 5_000 });

        // Re-click Columns to close it before opening Filters so the popovers
        // don't fight for focus.
        await page.GetByRole(AriaRole.Button, new() { Name = "Columns" }).ClickAsync();

        await page.GetByRole(AriaRole.Button, new() { Name = "Filters" }).ClickAsync();
        // The Filters popover renders an "Add filter" affordance; assert
        // *some* dialog/popover content rendered by checking the role=dialog.
        // Mantine Popovers in interactive mode use role="dialog".
        await Assertions.Expect(page.GetByRole(AriaRole.Dialog).First)
            .ToBeVisibleAsync(new() { Timeout = 5_000 });
    }
}
